<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PlatformTarget>x64</PlatformTarget>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <AssemblyName>Museek</AssemblyName>
    <RootNamespace>Museek</RootNamespace>
    <ApplicationIcon>Assets/Museek.ico</ApplicationIcon>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <Version>1.3.2</Version>
    <Product>Museek</Product>
    <Description>A simple audio player, trimmer and tag editor for Windows.</Description>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Museek.Core/Museek.Core.csproj" />
    <PackageReference Include="LibVLCSharp" Version="3.10.1" />
    <PackageReference Include="VideoLAN.LibVLC.Windows" Version="3.0.24" />
    <PackageReference Include="TagLibSharp" Version="2.3.0" />
  </ItemGroup>
</Project>
